// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Http = NewAsset("http.c", "2e80cff564ff054b93ae2c195075009d94e53c9c1f9b60acc208afd8eaabdbb2")
