// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Http = NewAsset("http.c", "a29e0000137ed3eb0d42432b96e395d99570e759e9c698c5cc88d75e30ea74ac")
