// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "9fad4b4b757a0ff3be5ba23ae348b267a0ce96d8dd72adc693f0826f868626b9")
