// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "592893ce326d14c66df1f904173e938167d0b9f1b9be5613becb6c4423acc17c")
