// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "6628aa209138dc98f7e9b397ab98f594ecf27eed561884b59622fa762e1f233c")
